### PR TITLE
Use conda-forge's default Fortran compiler on Windows

### PR DESCRIPTION
**Pull request by bnavigator**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed) (no)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Avoid specifying flang (see https://github.com/conda-forge/blas-feedstock/issues/106)

### CODE REVIEW

**Comment by bnavigator** [comment]
@conda-forge-admin, please rerender

**Comment by roryyorke** [comment]
Will try to look this weekend, unfortunately can't promise that I will.

**Comment by moorepants** [comment]
This seems fine to me. The use of flang in the past is because there may have not been a default fortran compiler on windows.

**Comment by bnavigator** [comment]
Yes, that's what I understand from the comments in https://github.com/conda-forge/blas-feedstock/issues/106 as well.
We added the flang >= 11 two years ago, but the comments in https://github.com/conda-forge/slycot-feedstock/pull/39, https://github.com/conda-forge/slycot-feedstock/pull/36 and https://github.com/python-control/Slycot/pull/160 did not record why exactly.

**Comment by bnavigator** [comment]
*I pressed merge and the main branch is updated. Somehow Github got confused a bit in the process. If this doesn't get resolved automatically, I will close manually in a bit.*

**Pull request closed without merging**
