### PR TITLE
Enable py 27 on Windows and OSX.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
This comes from the appveyor fail:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - openblas=0.3.3
  - python=2.7
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by moorepants** [comment]
And the failure on azure for osx py27:

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
export PREFIX=/usr/local/miniconda/conda-bld/slycot_1556984365979/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
export SRC_DIR=/usr/local/miniconda/conda-bld/slycot_1556984365979/test_tmp
import: 'slycot'
Traceback (most recent call last):
  File "/usr/local/miniconda/conda-bld/slycot_1556984365979/test_tmp/run_test.py", line 2, in <module>
    import slycot
  File "/usr/local/miniconda/conda-bld/slycot_1556984365979/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python2.7/site-packages/slycot/__init__.py", line 16, in <module>
    from .analysis import ab01nd,ab05md,ab05nd,ab07nd,ab08nd, \
  File "/usr/local/miniconda/conda-bld/slycot_1556984365979/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python2.7/site-packages/slycot/analysis.py", line 21, in <module>
    from . import _wrapper
ImportError: cannot import name _wrapper
Tests failed for slycot-0.3.4.0-py27h919474f_0.tar.bz2 - moving package to /usr/local/miniconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for slycot-0.3.4.0-py27h919474f_0.tar.bz2 - moving package to /usr/local/miniconda/conda-bld/broken
TESTS FAILED: slycot-0.3.4.0-py27h919474f_0.tar.bz2
##[error]Bash exited with code '1'.
```

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
Now getting this on the windows build:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - openblas -> libflang[version='>=5.0.0'] -> openmp==5.0.0 -> vc=14
  - vc=9
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by moorepants** [comment]
So it seems as if openmp 5 is required but it only works with vc 14 but py 27 requires vc 9.

**Comment by murrayrm** [comment]
I've been thinking of suggesting that python-control drop support for Python 2.7 given that it is getting deprecated soon anyway.  Anyone still using py27 would have to use an older version.

Should we do that for slycot (which would then require the same change for python-control)?

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
> I've been thinking of suggesting that python-control drop support for Python 2.7 given that it is getting deprecated soon anyway. Anyone still using py27 would have to use an older version.

According to most statistics there are huge numbers of people using python 2.7. I personally am curious what will happen come Jan 1 2020 given that fact. Slycot and python-control can decide to drop support whenever they like, but until that happens I'd like to support what those packages claim to support.

> Should we do that for slycot (which would then require the same change for python-control)?

I'm personally wary about dropping 2.7. I think for downstream packages like python-control and slycot we should just watch numpy/scipy etc. When they do, we can do it. So that those communities front the backlash and support issues (if any).

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
Current failures on the osx 27 build:
```
- Check for working C compiler: $BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang -- broken
CMake Error at /usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/local/miniconda/conda-bld/slycot_1556990016425/_build_env/bin/x86_64-apple-darwin13.4.0-clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /usr/local/miniconda/conda-bld/slycot_1556990016425/work/_cmake_test_compile/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_d1114/fast 
    /Applications/Xcode_10.1.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_d1114.dir/build.make CMakeFiles/cmTC_d1114.dir/build
    Building C object CMakeFiles/cmTC_d1114.dir/testCCompiler.c.o
    /usr/local/miniconda/conda-bld/slycot_1556990016425/_build_env/bin/x86_64-apple-darwin13.4.0-clang   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/usr/local/miniconda/conda-bld/slycot_1556990016425/work=/usr/local/src/conda/slycot-0.3.4.0 -fdebug-prefix-map=/usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6   -o CMakeFiles/cmTC_d1114.dir/testCCompiler.c.o   -c /usr/local/miniconda/conda-bld/slycot_1556990016425/work/_cmake_test_compile/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_d1114
    /usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d1114.dir/link.txt --verbose=1
    /usr/local/miniconda/conda-bld/slycot_1556990016425/_build_env/bin/x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/usr/local/miniconda/conda-bld/slycot_1556990016425/work=/usr/local/src/conda/slycot-0.3.4.0 -fdebug-prefix-map=/usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -L/usr/local/miniconda/conda-bld/slycot_1556990016425/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib  CMakeFiles/cmTC_d1114.dir/testCCompiler.c.o  -o cmTC_d1114 
    ld: library not found for -lcrt1.10.6.o
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_d1114] Error 1
    make: *** [cmTC_d1114/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (ENABLE_LANGUAGE)
```

**Pull request closed without merging**
