### PR TITLE
TEST: new f2py entry points by numpy dev channel

### PR DESCRIPTION
**Pull request by bnavigator**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bnavigator** [comment]
@conda-forge-admin, please rerender

**Comment by bnavigator** [comment]
This is a test for https://github.com/conda-forge/numpy-feedstock/pull/277

**Comment by h-vetinari** [comment]
Curious where osx-arm seems to be looking for numpy:
```
from: can't read /var/mail/numpy.f2py.f2py2e
```

**Comment by bnavigator** [comment]
Nah that is bahs interpreting the python `from` statement

**Comment by bnavigator** [comment]
It's still ignoring the shebang, or the shebang is wrong. Maybe the cross-python setup interferes after all.

**Comment by bnavigator** [comment]
My guess is there is a literal '$BUILD_PREFIX' in the entry-point script shebang. My hope was that through the changes in conda-forge/numpy-feedstock#277 that would be properly replaced by the conda-build or install. Apparently that is not the case.

**Pull request closed without merging**
