### PR TITLE
Fixes for Windows, Mac ARM, and Linux builds

### PR DESCRIPTION
**Pull request by bnavigator**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- Supersedes #36 
- Fixes the failures seen in #35, debugged in #38.
- Needs a retrigger of ~#35~ the PR to be opened by the OS-X migrator bot

### CODE REVIEW

**Comment by bnavigator** [comment]
@conda-forge-admin, please rerender

**Review by murrayrm — APPROVED** [review]
I look through @bnavigator changes and these seem fine.  There are also a bunch of re-rendered changes that are too complex to confirm are OK (but presumably they are fine)...

**Comment by zonut321** [comment]
> 
> Checklist
> * [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
> * [x] Bumped the build number (if the version is unchanged)
> * [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
> * [x] Ensured the license file is being packaged.
> 
> - Supersedes #36 
> - Fixes the failures seen in #35, debugged in #38.
> - Needs a retrigger of #35

❄️

**Comment by bnavigator** [comment]
@murrayrm, anything keeping this from merging?

**Comment by bnavigator** [comment]
@conda-forge-admin, please rerender

**Comment by murrayrm** [comment]
Linux builds are failing.  The error is 
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". 
CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```
???

**Comment by bnavigator** [comment]
@conda-forge-admin, please rerender

**Comment by bnavigator** [comment]
After I explicitly added (gnu) make to the recipe, the Linux builds succeed now. There must have been a transitive dependency change in the scikit-build or cmake package.

**Comment by bnavigator** [comment]
@conda-forge-admin, please rerender

**Comment by bnavigator** [comment]
ready to merge

**Pull request merged**
